### ISSUE TITLE
[Enhancement] Bow & Crossbow crosshair

### ISSUE THREAD

**Issue by vos6434** [ZaOrlando/crosshairmod#1]
Make a new crosshair for the bow and crossbow or use the existing attract crosshair.

**Comment by KiOrlando** [comment]
This will be added in the next update! Thanks for the suggestion

**Comment by vos6434** [comment]
New idea haha
show the attack crosshair when the bow/crossbow is fully charged.

**Comment by vos6434** [comment]
Welp that was a brain fart, both issues were made by me haha
