### ISSUE TITLE
[Invalid] Change crosshair option

### ISSUE THREAD

**Issue by liabri** [ZaOrlando/crosshairmod#10]
I think a way to change the crosshairs would be nice, I'm personally not a fan of the singular dot as the basic crosshair

**Comment by vos6434** [comment]
You can change the crosshairs with a texturepack. No need for a whole option setting imo

**Comment by liabri** [comment]
Oh! For some odd reason that did not come to mind whatsoever... Well thanks for enlightening me x) I think you can close this issue.
