### ISSUE TITLE
drawTexture for default case is called with modified args in InGameHudMixin leading to mod incompatibility

### ISSUE THREAD

**Issue by qualterz** [ZaOrlando/crosshairmod#11]
There is a problem that the original arguments are not passed to the `drawTexture` method, and this causes incompatibility with other mods

https://github.com/ZaOrlando/crosshairmod/blob/0b70fee378b8019fa178ba949733b9f7da311b00/src/main/java/zaorlando/crosshairmod/mixin/InGameHudMixin.java#L33-L56

For example, if some other mod modifies `x` and `y` arguments, this mod replaces this modifications with own values

https://github.com/ZaOrlando/crosshairmod/blob/0b70fee378b8019fa178ba949733b9f7da311b00/src/main/java/zaorlando/crosshairmod/mixin/InGameHudMixin.java#L45

**Comment by qualterz** [comment]
This is why [Lookaround!](https://github.com/qualterz/lookaround) mod does not working correctly with this mod, [here](https://github.com/qualterz/lookaround/blob/0620242bb57de917290866daa335650d8a0c1dc6/src/main/java/me/qualterz/minecraft/lookaround/mixin/InGameHudMixin.java#L63-L70) arguments are modified

**Comment by KiOrlando** [comment]
Good catch! I'll get a fix out soon,

**Comment by KiOrlando** [comment]
https://github.com/ZaOrlando/crosshairmod/blob/0b70fee378b8019fa178ba949733b9f7da311b00/src/main/java/zaorlando/crosshairmod/mixin/InGameHudMixin.java#L33-L56

Replacing line 45 with `InGameHud.drawTexture(matrices, x, y, 0, 0, 15, 15, 15, 15);` and replacing line 54 with `inGameHud.drawTexture(matrices, x, y, u, v, width, height);` should fix some other potential incompatibilities like this one.

**Comment by KiOrlando** [comment]
The updated jar has been published on curseforge for download!
