### ISSUE TITLE
Smooth changing of the crosshair

### ISSUE THREAD

**Issue by Lyapsus** [ZaOrlando/crosshairmod#12]
Smooth changing of the crosshair like in https://www.curseforge.com/minecraft/mc-mods/hello-crosshair

**Comment by KiOrlando** [comment]
Hello crosshair is not an open source project and all rights are reserved by the creator of that mod as stated in their license. If I attempt to copy that idea, it would be copyright infringement

**Comment by Lyapsus** [comment]
Wait, we can't implement the very idea to make crosshair dynamic like that? Bethesda should be nervous (as well as TinyBuild itself).

![gif-08-18-21-07-29-23-pm](https://user-images.githubusercontent.com/37628546/175823851-4e43f758-506a-4923-84a0-b2552f5193a1.gif)

**Comment by KiOrlando** [comment]
It would be infringing because it is the only defining feature that mod has compared to this one, they choose a closed license and I choose to respect that. Locking
