### ISSUE TITLE
1.19 support?

### ISSUE THREAD

**Issue by Vi-Tul** [ZaOrlando/crosshairmod#14]
When 1.19 - 1.19.2 version will be released?

**Comment by ghost** [comment]
I'd also like to see a 1.19.2 version; I like this better than Dynamic Crosshair. Zaorlando hasn't been online in 3 months though so I guess we'll have to wait and see.

**Comment by Vi-Tul** [comment]
> I'd also like to see a 1.19.2 version; I like this better than Dynamic Crosshair. Zaorlando hasn't been online in 3 months though so I guess we'll have to wait and see.

Btw, I already fixed this issue. You just need to change literally five strings in text files inside of .jar (like fabric.mod or smth like that, i don't remember). If you need, i can upload instructions or the modified... mod 😆

**Comment by ghost** [comment]
> > I'd also like to see a 1.19.2 version; I like this better than Dynamic Crosshair. Zaorlando hasn't been online in 3 months though so I guess we'll have to wait and see.
> 
> Btw, I already fixed this issue. You just need to change literally five strings in text files inside of .jar (like fabric.mod or smth like that, i don't remember). If you need, i can upload instructions or the modified... mod 😆

Oh thanks, I forgot that sometimes works. Just did it myself and I've got the mod working on 1.19.2 now.

**Comment by KiOrlando** [comment]
1.19 version is released now
