### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by Vi-Tul** [ZaOrlando/crosshairmod#15]
Basically the title. Great mod, btw

**Comment by KiOrlando** [comment]
Is there an error on loading? 1.19.4 should be compatible

**Comment by Vi-Tul** [comment]
Yep, here is the crash log
[crash-2023-04-29_19.46.30-client.txt](https://github.com/KiOrlando/crosshairmod/files/11359440/crash-2023-04-29_19.46.30-client.txt)

**Comment by Vi-Tul** [comment]
@KiOrlando, any updates?

**Comment by KiOrlando** [comment]
v0.5.1 adds 1.19.4 support, It has now been released on curseforge

**Comment by KiOrlando** [comment]
Thank you for the continued support!

**Comment by Vi-Tul** [comment]
No, thank YOU for this amazing mod and continued support of it!
