### ISSUE TITLE
[Mod Conflict] w/ LessClutter

### ISSUE THREAD

**Issue by Kratos-Lee520** [ZaOrlando/crosshairmod#3]
There is no crosshair when holding any tools, so it makes it difficult to hit mobs with bows or swords without a crosshair telling me how to adjust my aim. Try seeing if the mod LessClutter is an issue.

Mod link: https://www.curseforge.com/minecraft/mc-mods/less-clutter
MC Version 1.17.1
Fabric Version 0.11.6
Crosshair Version 0.3.1

**Mod List:                            Version:**

Appleskin                             2.0.0
Architectury                         2.1.20
AudioOutput                        0.0.4
AutoSmeltEnchant               1.1.0
AxesAreWeapons                 1.3
basicAIOTs                            1.3.1
BCLib                                    0.2.0
BeetleOrigin                         2.0
BetterBiomeBlend                1.1.8
BetterDroppedItems            1.3.0
BetterEnd                             0.10.2
BetterMinecshafts                1.0.0
BetterNether                        5.1.3
BetterStrogholds                  1.0
BetterThirdPerson                1.5.0
CavesAndCliffsAdditions     1.2.1
Carrier                                  1.8.0
CavesAndCliffsAddonForWilliamWythersOverhauledOverworld  1.1
Charm                                  3.3.0
Charmonium                       3.3.0
CleanCut                             4.0
ClothAPI                              2.0.54
ClothConfig                         5.0.34
ConsularOrigins                   1.2.1
ContinueButton                    1.0.4
ControllingForFabric              1.2.0
Coupling                                1.5.1
Croptopia                               1.5.0
CrosshairMod                          0.3.1
CullLeaves                              2.2.0
CustomFog                            1.6.0
DualWeilding                         1.0.6
DurabilityViewer                     1.10.1
EasyUpdate                             1.0.1
ExpandedArmorEnchanting     1.0.1
ExpandedStorage                     7.0.0
ExtraOrigins                              6
FabricAPI                                  0.36.1
FabricFurnaces                         2.0.1
FabricLanguageKotlin              1.6.2           &                  Kotlin   1.5.2
Seasons                                    1.2.2
FallingLeaves                            1.7.2
FallingTree                                2.12.1
FastFurnace                              3.0
FPSDisplay                               1.4.1
Graves                                     1.0.6
Iris                                           1.1.0             &                Sodium   0.3.0  Iris1Rev.7491e3a
Krypton                                   0.1.4
LambdaBetterGrass                1.2.0
LapisReserve                           1.0.8
LazyDFU                                  0.1.2
LessClutter                              1.1.9
Lithium                                    0.7.3
MedievalWeapons                  1.1.5
ModMenu                               2.0.2
MoreBlockBricks                     1.1.1
MoreStructuresForWilliamWythersOverhauledOverworld  1.1
MoStructures                          1.2.1
MouseWheelie                        1.7.3
NoRecipeBook                         2.1
NotEnoughCrashes                 3.3.1
OKZoomer                              5.0.0Beta2
Origins                                    1.0.2
OriginsClasses                        1.2.1
ParadoxSlabs                          0.1.1
Pehkui                                     2.2.1
PreciseBlockPlacing                1.07
ResPackOpts                           2.1.1
RoughlyEnoughItems             6.0.264
SimpleBackpack                     1.1.13
SoundPhysics                         1.1.1
Stepup                                    0.27.2-1.1
TaxFreeLevels                         1.2.1
TomsStorage                          1.1.13
ToroHealth                              7
VanillaExcavators                     2.2.0
VanillaHammers                      3.1.2
WilliamWythersOverhauledOverworld   1.5
WhatTheHellIsThat                 3.7.0
XaerosMinimap                      21.12.5.1
XaerosWorldmap                   1.14.5.2
YungsAPI                                11

**Comment by KiOrlando** [comment]
The issue seems to be with the 'dynamic crosshair' feature of LessClutter, in the LessClutter config file you can disable that feature and restart your game and everything should work as intended

**Comment by Kratos-Lee520** [comment]
okay I will try it.

**Comment by Kratos-Lee520** [comment]
Yes that did work, awesome! Thank you!
