### ISSUE TITLE
[Mod Conflict] w/ Flour's Various Tweaks

### ISSUE THREAD

**Issue by Nekkok** [ZaOrlando/crosshairmod#5]
With the awesome update made to 1.18.x is such a shame I can't make it work. The game just crashes throws this log:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_329 failed
Código de error: -1

Minecraft version: 1.18
Fabric version: 0.12.12

Latest Iris + Sodium are installed

**Comment by KiOrlando** [comment]
I will look into this,

**Comment by KiOrlando** [comment]
I cant seem to reproduce your issue. Can you provide a full mod list along with your .minecraft\config\sodium-options.json and .minecraft\config\iris.properties files?

**Comment by Nekkok** [comment]
Sodium

{
  "quality": {
    "weather_quality": "FANCY",
    "leaves_quality": "FANCY",
    "enable_vignette": true
  },
  "advanced": {
    "arena_memory_allocator": "ASYNC",
    "allow_direct_memory_access": true,
    "enable_memory_tracing": false,
    "use_advanced_staging_buffers": true,
    "cpu_render_ahead_limit": 3
  },
  "performance": {
    "chunk_builder_threads": 0,
    "always_defer_chunk_updates": false,
    "animate_only_visible_textures": true,
    "use_entity_culling": true,
    "use_particle_culling": true,
    "use_fog_occlusion": true,
    "use_block_face_culling": true
  },
  "notifications": {
    "hide_donation_button": false
  }
}

**Comment by Nekkok** [comment]
Iris

axShadowRenderDistance=32
shaderPack=ComplementaryShaders_v4.3.2.zip
enableShaders=false

**Comment by Nekkok** [comment]
And my "tiny" modlist...

achievementplates-1.18+-1.6.jar
AdditionalAdditions-3.0.1.jar
AdvancedCompass-fabric-1.18-1.2.6.jar
AdvancementPlaques-1.18-fabric-1.4.3.jar
advancements-enlarger-0.2.4.jar
adventurez-1.4.5.jar
agb-1.18-1.0.3.jar
All+Arrows+Infinity+Fix-FABRIC-1.0.0-MC-1.18.jar
amecs-1.3.4+mc.1.18-pre1.jar
Amplifier+Nether+1.0.1+_+Fabric.jar
anvil-crushing-recipes-1.3.2-b1+MC1.18-1.18.1.jar
AnvilFormat-1.1.jar
appleskin-fabric-mc1.18-2.2.0.jar
architectury-3.2.49.jar
armor-stand-editor-1.3.1+1.18-rc3.jar
arrp-0.5.4.jar
audaki-cart-engine-mc1.18-fabric-v1.0.1.jar
autorun-1.18.X-0.3.0.jar
auto_third_person-1.18-1.1.0.jar
AwesomeDungeonOcean-Fabric-1.18-1.0.2.jar
axolotl-item-fix-1.1.3.jar
balm-fabric-2.1.0+0.jar
bedbenefitsfabric-1.18-0.1.0.jar
bedspreads-fabric-1.5.0-1.18.jar
better-enchanted-books-1.17-1.2.12.jar
betterbeacon-1.0.7.jar
betterbeaconplacement-fabric_1.18.x-1.4.jar
betterbeds-1.2.0.jar
BetterF3-1.2.1-Fabric-1.18.jar
bettermounthud-1.1.3.jar
bettersleeping-0.5.1+1.18.jar
BetterTaskbar-1.18-Fabric-1.1.jar
BetterThirdPerson-Fabric-1.18-1.5.4.jar
blur-2.4.1.jar
boat-fall-1.1.0.jar
boatcontainer-1.0.4.jar
bouncierbeds-fabric_1.18.x-1.0.jar
breedablekillerrabbit-fabric_1.18.x-1.5.jar
cakechomps-fabric-1.4.0-1.18.jar
Chunky-1.2.153.jar
cleancut-1.18-4.0-fabric.jar
clickadv-fabric-2.1.jar
cloth-config-6.0.45-fabric.jar
Clumps-fabric-1.18-8.0.1.jar
collective-fabric-1.18.x-3.9.jar
colorfulsubtitles-1.0.0.jar
CompactStatusEffects-2.1.0.jar
conduitspreventdrowned-fabric_1.18.x-1.5.jar
ConnectedGlass_1.18.1_v03.jar
continuity-1.0.3+1.18.jar
cool_elytra-1.3.1.jar
copper-blocks-fix-1.0.1.jar
copperequipment-1.18.jar
Couplings-1.7.1+1.18.jar
craftingtweaks-fabric-1.18-13.0.0.jar
creeperaiupdated-fabric-1.5.0.jar
cryingportals-fabric_1.18.x-1.0.jar
custom-stars-0.7+1.18.jar
cyclepaintings-fabric_1.18.x-2.1.jar
DamageTilt-1.18-fabric-0.1.2.jar
deepslatecutting-1.18-1.3.0.jar
defaultoptions-fabric-1.18-14.0.0.jar
despawningeggshatch-fabric_1.18.x-2.3.jar
DisableCustomWorldsAdvice-1.4.jar
discerning-furnace-1.0.5+MC1.18-1.18.1.jar
discontinuous-beacon-beams-1.1.1+MC1.18-1.18.1.jar
dismountentity-fabric_1.18.x-1.5.jar
doubledoors-fabric_1.18.x-3.1.jar
DripSounds-1.18-0.3.0.jar
DungeonsArise-1.18.1-2.1.49b-fabric-beta.jar
dynamic-fps-2.0.6.jar
DynamicSoundFilters-1.3.0+1.18.jar
Earth2Java-1.7.4+1.18.jar
easyelytratakeoff-fabric_1.18.x-2.2.jar
EasyMagic-v3.0.0-1.18-Fabric.jar
eating-animation-1.2.jar
edibles-fabric_1.18.x-2.4.jar
effective-1.0.jar
eldritch-mobs-1.10.1.jar
elytratrinket-fabric-3.0.0-1.18.1.jar
EnchantmentDescriptions-Fabric-1.18-8.0.3.jar
EntityCulling-Fabric-1.3.3.jar
EquipmentCompare-1.18-fabric-1.2.9.jar
extractpoison-fabric_1.18.x-1.6.jar
extrasounds-2.0.2+1.18.jar
extrasounds-2.1.1+1.18.jar
Fabric-1.18-SmoothSwapping-0.4.3.jar
fabric-api-0.44.0+1.18.jar
fabric-branders-spawnermod-1.18-1.1.2.jar
fabric-experiencebugfix-1.18-18.jar
fabric-language-kotlin-1.7.0+kotlin.1.6.0.jar
fabrication-1.18-2.2.1-exp4.jar
fabrication-1.18-2.3.0.jar
fallingleaves-1.8.0+1.18.jar
FallingTree-1.18.1-2.16.0.jar
fastfurnace-1.18-4.jar
ferritecore-4.0.0-fabric.jar
Fireplace-Lib-6.2.2+1.18.jar
firespreadtweaks-fabric_1.18.x-1.2.jar
fireworkfrenzy-1.7.jar
firstperson-fabric-2.1.0-mc1.18-pre1.jar
fishontheline-fabric_1.18.x-1.2.jar
FolderList.txt
ForgeConfigAPIPort-v3.1.0-1.18.1-Fabric.jar
fuelinfo-1.0-SNAPSHOT.jar
furnacerecycle-fabric_1.18.x-1.0.jar
fvt-fabric-1.8.0-mc1.18.jar
giantspawn-fabric_1.18.x-2.7.jar
grassseeds-fabric_1.18.x-1.6.jar
grizzlybear-1.18-1.2.1.jar
herdspanic-1.0.3.jar
Highlighter-1.18-fabric-1.1.2.jar
hoetweaks-fabric_1.18.x-1.2.jar
horse-stats-vanilla-4.1.10.jar
HorseBuff-1.18-pre5-1.1.2.jar
ice-boat-nerf-1.0.8+MC1.18.jar
Iceberg-1.18-fabric-1.0.27.jar
icepreventscropgrowth-fabric_1.18.x-1.4.jar
illuminations-1.10.2.jar
indium-1.0.2-alpha1+mc1.18.jar
indypets-0.7.1.jar
inventory-control-tweaks-1.3.12+MC1.18-1.18.1.jar
inventoryessentials-fabric-1.18-4.0.0.jar
iris-mc1.18.1-1.1.3.jar
ItemBorders-1.18-fabric-1.1.4.jar
itemscroller-fabric-1.18.0-0.15.0.jar
justenoughkeys-0.4.2-fabric.jar
KeepHeadNames-1.5.1-fabric-1.18.jar
keepmysoiltilled-fabric_1.18.x-1.0.jar
Kiwi-1.18-5.1.0.jar
kleeslabs-fabric-1.18-11.0.0.jar
konkrete_fabric_1.3.2_MC_1.18.jar
krypton-0.1.5.jar
lazydfu-0.1.2.jar
leadable-bats-1.0.1.jar
lenientstacksize-1.3.0.jar
LoudLeads-1.0.1+mc1.18.jar
maessentials-1.18-3.7.1.jar
malilib-fabric-1.18.0-0.10.0-dev.26.jar
Mambience-3.2.0+1.18.jar
map-atlases-1.3.0-v1dot18.jar
mavm-1.0.5.jar
megane-6.1.0.jar
MerchantMarkers-1.18.1-fabric-1.1.0.jar
minimalmenu-1.18.1-0.1.0.jar
modmenu-3.0.0.jar
mooshroomspawn-fabric_1.18.x-1.5.jar
mooshroomtweaks-fabric_1.18.x-1.6.jar
morebannerfeatures-1.1.2-1.18.jar
morechathistory-1.18-1.1.0.jar
mostructures-1.3.0-pre1-1.18.jar
MouseTweaks-fabric-mc1.18-2.18.jar
mousewheelie-1.8.0+mc1.18-pre5.jar
music-duration-reducer-1.0.0.jar
namepain-1.4.0+fabric-1.17.x.jar
nether-piglin-mod-1.2.0.jar
netherite-horse-armor-1.4.0.jar
netherportalfix-fabric-1.18-9.0.0.jar
netherportalspread-fabric_1.18.x-5.6.jar
Nimble-1.18-pre7-fabric-2.0.0.jar
nohostilesaroundcampfire-fabric_1.18.x-3.8.jar
nomoreglowingpots-1.0.2.jar
notenoughanimations-fabric-1.4.0-mc1.18-pre1.jar
notenoughcrashes-4.1.3+1.18-fabric.jar
npc-variety-1.18-2.2.1.jar
onsoulfire-1.18-1.jar
paperbooks-fabric_1.18.x-1.4.jar
PerfectAccuracy-1.2.jar
pling-1.5.0.jar
powershot-1.4.0-1.18-fabric.jar
PresenceFootsteps-1.4.0.jar
PuzzlesLib-v3.0.1-1.18-Fabric.jar
quickpaths-fabric_1.18.x-1.9.jar
randomsheepcolours-fabric_1.18.x-1.6.jar
reeses_sodium_options-mc1.18-1.2.3.jar
replantingcrops-fabric_1.18.x-2.5.jar
repurposed_structures_fabric-3.1.6+1.18.0.jar
RoughlyEnoughItems-7.0.346.jar
saturation-fixer-1.0.0.jar
scaffoldingdropsnearby-fabric_1.18.x-1.5.jar
second-chance-1.3.0.jar
shulkerboxtooltip-3.0.5+1.18.jar
sihywtcamc-1.4.1+1.18.jar
skeletonhorsespawn-fabric_1.18.x-1.9.jar
slimyfloor-1.18-1.2.2.jar
smarterfarmers-1.18-1.2.1.jar
smoothboot-fabric-1.18-1.7.0.jar
snowballsfreezemobs-fabric_1.18.x-1.5.jar
snowy-trees-1.0.0.jar
sodium-extra-mc1.18-0.3.7.jar
sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar
softerhaybales-fabric_1.18.x-1.5.jar
spark-fabric.jar
spidersproducewebs-fabric_1.18.x-1.5.jar
starlight-1.0.0+fabric.d0a3220.jar
stendhal-1.2.0-1.18.jar
stitched-snow-1.0.4.jar
styled-chat-1.2.2+1.18.jar
talkbubbles-1.0.1.jar
Terralith_v2.0.5___Fabric+Forge.jar
TieFix-1.7.1.jar
TinySkeletons-v3.0.0-1.18-Fabric.jar
titlefixer-1.0+1.18.jar
tooltipfix-1.0.4-1.18.jar
torohealth-1.18-fabric-1.jar
totemplus-1.2-1.18.1.jar
trinkets-3.1.0.jar
trulytreasures-fabric-1.18-1.0.1.jar
unvotedandshelved-1.0.3.jar
villagerdrops-1.18.jar
villagespawnpoint-fabric_1.18.x-1.8.jar
visuality-0.3.3-1.18-fabric.jar
VisualWorkbench-v3.0.0-1.18-Fabric.jar
Void-Fog-2.6.1.jar
vulnerableflight-1.0.0.jar
WaveyCapes-fabric-1.0.4-mc1.18-pre1.jar
weakerspiderwebs-fabric_1.18.x-2.0.jar
WitherTurnsSkeletons-1.1.0-1.18.0.jar
wooltweaks-fabric_1.18.x-1.4.jar
wthit-fabric-4.3.0.jar
zombiehorsespawn-fabric_1.18.x-3.0.jar
zombieproofdoors-fabric_1.18.x-1.4.jar

**Comment by KiOrlando** [comment]
This is a direct conflict with Flour's Various Tweaks (fvt-fabric-1.8.0-mc1.18.jar), it adds a feature that is not compatible with this mod.

**Comment by Nekkok** [comment]
Perfect, thanks!
