### ISSUE TITLE
[Enhancement] Suggestion about more explanatory name and description

### ISSUE THREAD

**Issue by egeesin** [ZaOrlando/crosshairmod#8]
I've maintaining my modpack for a long time, comparing lots of alternative mods, keeping description info in order to remind myself which specific mod does modify etc. Then I realized the current name it's not really addressing/explaining the capabilities of this mod enough.

The name gives initial clue that this mod modifies the crosshair itself or it's all about crosshair for sure but since this mod has a single and useful feature that most crosshair related mods haven't, I think it deserves more declerative/specific verb for the "Crosshair Mod".

Reading comments of the original Reddit post which you inspired to create this mod, I filtered out a couple of name ideas listed below, (also included my own idea):
- Situational Crosshair
- Dynamic Crosshair

**Comment by KiOrlando** [comment]
Fixed, thank you for the suggestion!
